test_homework_answer (test_case.test_yzt.TestYzt) ... ok
test_more_upload_detail (test_case.test_yzt.TestYzt) ... FAIL

======================================================================
FAIL: test_more_upload_detail (test_case.test_yzt.TestYzt)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\licha\PycharmProjects\AutomatedProject\test_case\test_yzt.py", line 28, in test_more_upload_detail
    self.assertEqual(result['code'],10)
AssertionError: 0 != 10

----------------------------------------------------------------------
Ran 2 tests in 1.351s

FAILED (failures=1)
